### ISSUE TITLE
[IS-3] Text is shaking inside a rectangle

### ISSUE THREAD

**Issue by kubsnn** [kerfuffin/spg-opengl#6]
When text is placed inside a rectangle and the rectangle is being moved, there is a noticeable shaking or jittering effect observed in the text. This behavior is not expected and can be distracting for users.

**Comment by Krabbens** [comment]
Unfortunately, I couldn't resolve this issue. However, I managed to implement a solution that effectively replaces the shaking with a system of gradual transitions.
